# Generated by Django 6.0.2 on 2026-03-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=50)),
                ('last_name', models.CharField(default='', max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('customer_type', models.CharField(choices=[('regular', 'Zwykły klient'), ('vip', 'VIP')], default='regular', max_length=10)),
                ('discount_percent', models.FloatField(default=0)),
                ('loyalty_points', models.IntegerField(default=0)),
            ],
            options={
                'ordering': ['first_name', 'last_name'],
            },
        ),
    ]
